### PR TITLE
Fix parsing of "--" for edit command

### LINKED ISSUE #352: [PE-D][Tester D] No way to remove an optional field (email or address) from a contact via edit
## Description

The `edit` command allows clearing all tags with `t/` (empty tag value), but there is no equivalent way to remove an email or address once set. Typing `e/` or `a/` with an empty value throws a validation error. The UG does not document any workaround.

## Steps to Reproduce

1. Add a contact with email and address:
   `add n/Test Person p/91110001 e/test@example.com a/123 Test Street`
2. Attempt to remove the email:
   `edit n/Test Person -- e/`
3. Attempt to remove the address:
   `edit n/Test Person -- a/`

## Expected Behaviour

- Step 2: email field removed from the contact.
- Step 3: address field removed from the contact.

## Actual Behaviour

- Step 2: Error — `Emails should be of the format local-part@domain...`
- Step 3: Error — `Addresses should only contain alphanumeric characters...`

**For comparison**, clearing tags works fine:
`edit n/Test Person -- t/` → tags successfully cleared.

There is no documented or functional way to remove an email or address once it has been set on a contact.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #364: [PE-D][Tester D] edit command fails when disambiguating by an address that contains ' --'
## Description

The `edit` command splits the input at the first occurrence of ` --` to separate the target segment from the update segment. If the disambiguating address itself contains ` --` (which is valid per the address format rules), the parser splits at the wrong position, breaking the command.

## Steps to Reproduce

1. Add two contacts with the same name (needed for disambiguation):
   ```
   add n/Double Dash p/91110007 a/Block 50 -- West Coast
   add n/Double Dash p/91110008 a/Clementi Ave
   ```
   Both succeed — an address containing ` --` is accepted by `add`. ✓

2. Now attempt to edit the first contact using address disambiguation:
   ```
   edit n/Double Dash a/Block 50 -- West Coast -- p/99990007
   ```

## Expected Behaviour

NAB identifies the contact at "Block 50 -- West Coast" and updates their phone number to `99990007`.

## Actual Behaviour

The parser finds the first ` --` inside the address value and splits there, producing:
- Target segment: `n/Double Dash a/Block 50` (truncated — missing `-- West Coast`)
- Update segment: `West Coast -- p/99990007` (garbled)

This results in a parse error or the wrong contact being targeted. The command cannot be completed.

## Notes

The address `Block 50 -- West Coast` is accepted without error by `add`, so NAB itself creates a situation where a valid contact cannot subsequently be edited via address disambiguation.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by nywled**
# Description
* Replaced `--` with `>>`
* Blocked input of `>>` in any field
  * blocked in Add and Edit. Existing Tag command already blocks it as tag cannot have <>
* UG and DG updated as well
* Added a/ e/ pfp/ to empty these fields

Exactly 94 LoC for functional code?

Closes #364

### CODE REVIEW

**Comment by SpaceMongoose** [comment]
For clarity 40 LoC (excluding test code, documentation code)

**Review by SpaceMongoose — APPROVED** [review]
- [x] The PR is sent from a fork, and is from a separate branch.
- [x] Commit messages comply with the [Git Conventions](https://nus-cs2103-ay2526-s2.github.io/website/admin/standardsAndConventions.html).

LGTM! 👍

**Review by bolasika — CHANGES_REQUESTED** [review]
Change and apply fix for the following PR:
- Bug listed in #352

**Comment by eejon** [comment]
> Change and apply fix for the following PR:
> 
>     * Bug listed in #352

@bolasika Does he have enough LoC?

**Comment by nywled** [comment]
Closes #352

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -43,6 +43,8 @@ public AddCommand parse(String args) throws ParseException {
         }
 
         argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ADDRESS, PREFIX_PHOTO);
+        ParserUtil.verifyNoReservedEditDelimiterInValues(argMultimap,
```
Comment (eejon) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:46]: Sorry what's this for? I don't recall `>` being a valid input for any parameters, so was wondering if this is necessary.

**Review by eejon — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java (hunk 1 above)
Comment (nywled) [reply src/main/java/seedu/address/logic/parser/AddCommandParser.java:46]: so that for whatever reason the user cannot put the `>>` inside any field. Extra guard

**Review by bolasika — APPROVED** [review]
LGTM 🔥
