### PR TITLE
Fix: Update event subcommand message

### LINKED ISSUE #346: [PE-D][Tester A] No Specific Details Provided in the Error Message when Users Type `event'
## Screenshot

Image
<br>

## Notes
It may be useful for the users if there are more information provided in the error message on how to continue with the `event` command. This will also make the error message consistent with other invalid command formats such as `add` without any parameter specified.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by SpaceMongoose**
## Summary
* 7 LoC (excluding test code)
Fixes #346

### CODE REVIEW

**Review by eejon — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/logic/parser/EventCommandParser.java [hunk 1]
```diff
@@ -6,18 +6,24 @@
...
 import seedu.address.logic.commands.DeleteEventCommand;
 import seedu.address.logic.commands.FindEventCommand;
-import seedu.address.logic.commands.HelpCommand;
 import seedu.address.logic.parser.exceptions.ParseException;
 
 /**
  * Parses input arguments and creates the corresponding event subcommand.
  */
 public class EventCommandParser implements Parser<Command> {
+    public static final String MESSAGE_USAGE = "The 'event' command requires a valid subcommand.\n"
```
Comment (bolasika) [inline src/main/java/seedu/address/logic/parser/EventCommandParser.java:15]: Check if you could save LoC for feature freeze by:
1. putting the putting it in one line 
2. Not more than 120 character per lines to pass the checkstyle

**Review by bolasika — APPROVED** [review]
LGTM 🔥 
Please check if you could save LoC

**Review by bolasika — APPROVED** [review]
LGTM 🔥
